"""empty message

Revision ID: 204
Revises: 203
Create Date: 2020-02-25 17:51:10.176298

"""
from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "204"
down_revision = "203"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("created", sa.DateTime(), nullable=True))
    op.add_column(
        "session", sa.Column("completion_percentage", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("session", "completion_percentage")
    op.drop_column("account", "created")
